server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka/"

spring:
  flyway:
    enabled: true
    locations: classpath:db/migration

  datasource:
    url: "jdbc:postgresql://localhost:5433/details-service"
    username: "postgres"
    password: "12345"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
